Drop TABLE IF EXISTS MEMBERS;
CREATE TABLE IF NOT EXISTS MEMBERS (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(255) NOT NULL,
    CONSTRAINT email_unique UNIQUE (email));